// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPK1Ls_KN3Nbk86_XlAVH8kaMotQseWM',
    appId: '1:210294542486:web:8b255be866336ca536f2b7',
    messagingSenderId: '210294542486',
    projectId: 'jewelora-af085',
    authDomain: 'jewelora-af085.firebaseapp.com',
    storageBucket: 'jewelora-af085.firebasestorage.app',
    measurementId: 'G-1L8YVZYRE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWMajqxnrgUCWp5bSrB-z-Hj08pQKd2vQ',
    appId: '1:210294542486:android:620fb1ebeb70c67a36f2b7',
    messagingSenderId: '210294542486',
    projectId: 'jewelora-af085',
    storageBucket: 'jewelora-af085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEszS6sTjk9kRIa5mzSYmZq3ofPP2ZRq8',
    appId: '1:210294542486:ios:402d8c5dc420c62336f2b7',
    messagingSenderId: '210294542486',
    projectId: 'jewelora-af085',
    storageBucket: 'jewelora-af085.firebasestorage.app',
    iosBundleId: 'com.example.jewelOra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEszS6sTjk9kRIa5mzSYmZq3ofPP2ZRq8',
    appId: '1:210294542486:ios:402d8c5dc420c62336f2b7',
    messagingSenderId: '210294542486',
    projectId: 'jewelora-af085',
    storageBucket: 'jewelora-af085.firebasestorage.app',
    iosBundleId: 'com.example.jewelOra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhPK1Ls_KN3Nbk86_XlAVH8kaMotQseWM',
    appId: '1:210294542486:web:673ece00c7eb93cf36f2b7',
    messagingSenderId: '210294542486',
    projectId: 'jewelora-af085',
    authDomain: 'jewelora-af085.firebaseapp.com',
    storageBucket: 'jewelora-af085.firebasestorage.app',
    measurementId: 'G-590GRGPHHY',
  );
}
